[2025-01-05 09:38:48,500] {processor.py:153} INFO - Started process (PID=4492) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:38:48,517] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 09:38:48,525] {logging_mixin.py:115} INFO - [2025-01-05 09:38:48,525] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:38:48,757] {logging_mixin.py:115} INFO - [2025-01-05 09:38:48,734] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
Traceback (most recent call last):
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py", line 9, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2025-01-05 09:38:48,760] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:38:49,033] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.580 seconds
[2025-01-05 09:40:09,761] {processor.py:153} INFO - Started process (PID=5225) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:40:09,773] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 09:40:09,780] {logging_mixin.py:115} INFO - [2025-01-05 09:40:09,780] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:40:09,993] {logging_mixin.py:115} INFO - [2025-01-05 09:40:09,949] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
Traceback (most recent call last):
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py", line 9, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2025-01-05 09:40:10,001] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:40:10,828] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.196 seconds
[2025-01-05 09:41:26,785] {processor.py:153} INFO - Started process (PID=5752) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:41:26,796] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 09:41:26,800] {logging_mixin.py:115} INFO - [2025-01-05 09:41:26,797] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:41:26,857] {logging_mixin.py:115} INFO - [2025-01-05 09:41:26,849] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
Traceback (most recent call last):
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py", line 9, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2025-01-05 09:41:26,860] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:41:27,041] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.284 seconds
[2025-01-05 09:54:24,964] {processor.py:153} INFO - Started process (PID=3301) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:54:24,965] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 09:54:24,966] {logging_mixin.py:115} INFO - [2025-01-05 09:54:24,966] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:54:24,988] {logging_mixin.py:115} INFO - [2025-01-05 09:54:24,985] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
Traceback (most recent call last):
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py", line 9, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2025-01-05 09:54:24,988] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:54:25,039] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.080 seconds
[2025-01-05 09:55:06,811] {processor.py:153} INFO - Started process (PID=3730) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:55:06,815] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 09:55:06,818] {logging_mixin.py:115} INFO - [2025-01-05 09:55:06,818] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:55:06,852] {logging_mixin.py:115} INFO - [2025-01-05 09:55:06,851] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
Traceback (most recent call last):
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py", line 9, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2025-01-05 09:55:06,853] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:55:06,912] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.111 seconds
[2025-01-05 09:55:43,291] {processor.py:153} INFO - Started process (PID=4127) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:55:43,294] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 09:55:43,295] {logging_mixin.py:115} INFO - [2025-01-05 09:55:43,295] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:55:43,307] {logging_mixin.py:115} INFO - [2025-01-05 09:55:43,306] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
Traceback (most recent call last):
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py", line 9, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2025-01-05 09:55:43,308] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:55:43,362] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.077 seconds
[2025-01-05 09:56:20,071] {processor.py:153} INFO - Started process (PID=4374) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:56:20,074] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 09:56:20,075] {logging_mixin.py:115} INFO - [2025-01-05 09:56:20,075] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:56:20,106] {logging_mixin.py:115} INFO - [2025-01-05 09:56:20,103] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
Traceback (most recent call last):
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py", line 8, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2025-01-05 09:56:20,106] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:56:20,141] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.079 seconds
[2025-01-05 09:56:53,809] {processor.py:153} INFO - Started process (PID=4728) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:56:53,813] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 09:56:53,814] {logging_mixin.py:115} INFO - [2025-01-05 09:56:53,814] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:56:53,838] {logging_mixin.py:115} INFO - [2025-01-05 09:56:53,837] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
Traceback (most recent call last):
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py", line 8, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2025-01-05 09:56:53,840] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:56:53,891] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.092 seconds
[2025-01-05 09:57:29,413] {processor.py:153} INFO - Started process (PID=4977) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:57:29,415] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 09:57:29,419] {logging_mixin.py:115} INFO - [2025-01-05 09:57:29,418] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:57:30,415] {logging_mixin.py:115} INFO - [2025-01-05 09:57:30,414] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
Traceback (most recent call last):
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py", line 9, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-01-05 09:57:30,415] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:57:30,438] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.048 seconds
[2025-01-05 09:57:55,897] {processor.py:153} INFO - Started process (PID=5269) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:57:55,898] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 09:57:55,899] {logging_mixin.py:115} INFO - [2025-01-05 09:57:55,899] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:57:56,537] {logging_mixin.py:115} INFO - [2025-01-05 09:57:56,535] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
Traceback (most recent call last):
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py", line 9, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-01-05 09:57:56,537] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:57:56,565] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.679 seconds
[2025-01-05 09:58:41,277] {processor.py:153} INFO - Started process (PID=5774) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:58:41,282] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 09:58:41,283] {logging_mixin.py:115} INFO - [2025-01-05 09:58:41,283] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:58:42,101] {logging_mixin.py:115} INFO - [2025-01-05 09:58:42,099] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
Traceback (most recent call last):
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py", line 9, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-01-05 09:58:42,101] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:58:42,131] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.865 seconds
[2025-01-05 09:59:18,322] {processor.py:153} INFO - Started process (PID=6145) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:59:18,325] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 09:59:18,327] {logging_mixin.py:115} INFO - [2025-01-05 09:59:18,326] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:59:19,090] {logging_mixin.py:115} INFO - [2025-01-05 09:59:19,087] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
Traceback (most recent call last):
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py", line 9, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-01-05 09:59:19,091] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 09:59:19,138] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.823 seconds
[2025-01-05 10:00:03,178] {processor.py:153} INFO - Started process (PID=6612) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:00:03,182] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:00:03,183] {logging_mixin.py:115} INFO - [2025-01-05 10:00:03,183] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:00:04,098] {logging_mixin.py:115} INFO - [2025-01-05 10:00:04,097] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
Traceback (most recent call last):
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py", line 9, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-01-05 10:00:04,101] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:00:04,146] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.973 seconds
[2025-01-05 10:00:34,605] {processor.py:153} INFO - Started process (PID=6795) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:00:34,607] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:00:34,611] {logging_mixin.py:115} INFO - [2025-01-05 10:00:34,610] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:00:35,643] {logging_mixin.py:115} INFO - [2025-01-05 10:00:35,642] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
Traceback (most recent call last):
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py", line 9, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-01-05 10:00:35,643] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:00:35,678] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.085 seconds
[2025-01-05 10:01:05,837] {processor.py:153} INFO - Started process (PID=7068) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:01:05,838] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:01:05,843] {logging_mixin.py:115} INFO - [2025-01-05 10:01:05,843] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:01:07,822] {logging_mixin.py:115} INFO - [2025-01-05 10:01:07,814] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
Traceback (most recent call last):
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py", line 9, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[2025-01-05 10:01:07,822] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:01:07,910] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 2.096 seconds
[2025-01-05 10:02:40,454] {processor.py:153} INFO - Started process (PID=7557) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:02:40,462] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:02:40,469] {logging_mixin.py:115} INFO - [2025-01-05 10:02:40,469] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:02:41,474] {logging_mixin.py:115} INFO - [2025-01-05 10:02:41,473] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
Traceback (most recent call last):
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py", line 45, in <module>
    python_callable=extract_data,op_kwargs={{'data_interval_end': 'data_interval_end.strftime("%Y-%m-%d")'}}
TypeError: unhashable type: 'dict'
[2025-01-05 10:02:41,477] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:02:41,538] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.092 seconds
[2025-01-05 10:03:31,685] {processor.py:153} INFO - Started process (PID=8061) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:03:31,686] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:03:31,689] {logging_mixin.py:115} INFO - [2025-01-05 10:03:31,689] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:03:33,101] {logging_mixin.py:115} INFO - [2025-01-05 10:03:33,098] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
Traceback (most recent call last):
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py", line 45, in <module>
    python_callable=extract_data,op_kwargs={{'data_interval_end': 'data_interval_end.strftime("%Y-%m-%d")'}}
TypeError: unhashable type: 'dict'
[2025-01-05 10:03:33,102] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:03:33,158] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.485 seconds
[2025-01-05 10:04:19,342] {processor.py:153} INFO - Started process (PID=8208) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:04:19,349] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:04:19,353] {logging_mixin.py:115} INFO - [2025-01-05 10:04:19,353] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:04:20,970] {logging_mixin.py:115} INFO - [2025-01-05 10:04:20,966] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
Traceback (most recent call last):
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py", line 45, in <module>
    python_callable=extract_data,op_kwargs={{'data_interval_end': 'data_interval_end.strftime("%Y-%m-%d")'}}
TypeError: unhashable type: 'dict'
[2025-01-05 10:04:20,970] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:04:21,021] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.727 seconds
[2025-01-05 10:05:14,621] {processor.py:153} INFO - Started process (PID=8273) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:05:14,629] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:05:14,637] {logging_mixin.py:115} INFO - [2025-01-05 10:05:14,637] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:05:18,213] {logging_mixin.py:115} INFO - [2025-01-05 10:05:18,209] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
Traceback (most recent call last):
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py", line 45, in <module>
    python_callable=extract_data,op_kwargs={{'data_interval_end': 'data_interval_end.strftime("%Y-%m-%d")'}}
TypeError: unhashable type: 'dict'
[2025-01-05 10:05:18,217] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:05:18,297] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 3.716 seconds
[2025-01-05 10:06:07,721] {processor.py:153} INFO - Started process (PID=8593) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:06:07,733] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:06:07,749] {logging_mixin.py:115} INFO - [2025-01-05 10:06:07,741] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:06:11,653] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:06:12,249] {logging_mixin.py:115} INFO - [2025-01-05 10:06:12,249] {manager.py:508} INFO - Created Permission View: can delete on DAG:weather_data
[2025-01-05 10:06:12,377] {logging_mixin.py:115} INFO - [2025-01-05 10:06:12,377] {manager.py:508} INFO - Created Permission View: can edit on DAG:weather_data
[2025-01-05 10:06:12,481] {logging_mixin.py:115} INFO - [2025-01-05 10:06:12,481] {manager.py:508} INFO - Created Permission View: can read on DAG:weather_data
[2025-01-05 10:06:12,497] {logging_mixin.py:115} INFO - [2025-01-05 10:06:12,489] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:06:12,617] {logging_mixin.py:115} INFO - [2025-01-05 10:06:12,617] {dag.py:2398} INFO - Creating ORM DAG for weather_data
[2025-01-05 10:06:12,789] {logging_mixin.py:115} INFO - [2025-01-05 10:06:12,785] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:06:13,001] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 5.328 seconds
[2025-01-05 10:16:16,280] {processor.py:153} INFO - Started process (PID=9112) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:16:16,286] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:16:16,288] {logging_mixin.py:115} INFO - [2025-01-05 10:16:16,288] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:16:17,091] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:16:17,111] {logging_mixin.py:115} INFO - [2025-01-05 10:16:17,110] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:16:17,135] {logging_mixin.py:115} INFO - [2025-01-05 10:16:17,135] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:16:17,150] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.885 seconds
[2025-01-05 10:16:52,147] {processor.py:153} INFO - Started process (PID=9370) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:16:52,148] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:16:52,148] {logging_mixin.py:115} INFO - [2025-01-05 10:16:52,148] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:16:52,516] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:16:52,536] {logging_mixin.py:115} INFO - [2025-01-05 10:16:52,536] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:16:52,554] {logging_mixin.py:115} INFO - [2025-01-05 10:16:52,554] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:16:52,567] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.423 seconds
[2025-01-05 10:17:28,321] {processor.py:153} INFO - Started process (PID=9698) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:17:28,324] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:17:28,325] {logging_mixin.py:115} INFO - [2025-01-05 10:17:28,325] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:17:28,638] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:17:28,646] {logging_mixin.py:115} INFO - [2025-01-05 10:17:28,645] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:17:28,657] {logging_mixin.py:115} INFO - [2025-01-05 10:17:28,657] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:17:28,667] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.350 seconds
[2025-01-05 10:18:02,985] {processor.py:153} INFO - Started process (PID=9890) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:18:02,986] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:18:02,987] {logging_mixin.py:115} INFO - [2025-01-05 10:18:02,987] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:18:03,260] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:18:03,267] {logging_mixin.py:115} INFO - [2025-01-05 10:18:03,267] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:18:03,278] {logging_mixin.py:115} INFO - [2025-01-05 10:18:03,278] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:18:03,289] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.306 seconds
[2025-01-05 10:18:39,265] {processor.py:153} INFO - Started process (PID=10147) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:18:39,266] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:18:39,267] {logging_mixin.py:115} INFO - [2025-01-05 10:18:39,266] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:18:39,726] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:18:39,745] {logging_mixin.py:115} INFO - [2025-01-05 10:18:39,744] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:18:39,767] {logging_mixin.py:115} INFO - [2025-01-05 10:18:39,767] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:18:39,789] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.527 seconds
[2025-01-05 10:19:14,487] {processor.py:153} INFO - Started process (PID=10406) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:19:14,489] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:19:14,491] {logging_mixin.py:115} INFO - [2025-01-05 10:19:14,490] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:19:15,014] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:19:15,036] {logging_mixin.py:115} INFO - [2025-01-05 10:19:15,034] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:19:15,064] {logging_mixin.py:115} INFO - [2025-01-05 10:19:15,064] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:19:15,093] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.612 seconds
[2025-01-05 10:19:51,688] {processor.py:153} INFO - Started process (PID=10645) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:19:51,690] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:19:51,691] {logging_mixin.py:115} INFO - [2025-01-05 10:19:51,691] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:19:52,063] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:19:52,075] {logging_mixin.py:115} INFO - [2025-01-05 10:19:52,074] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:19:52,090] {logging_mixin.py:115} INFO - [2025-01-05 10:19:52,089] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:19:52,104] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.420 seconds
[2025-01-05 10:20:26,081] {processor.py:153} INFO - Started process (PID=10833) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:20:26,082] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:20:26,083] {logging_mixin.py:115} INFO - [2025-01-05 10:20:26,083] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:20:26,778] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:20:26,856] {logging_mixin.py:115} INFO - [2025-01-05 10:20:26,855] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:20:26,898] {logging_mixin.py:115} INFO - [2025-01-05 10:20:26,897] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:20:26,937] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.862 seconds
[2025-01-05 10:21:07,406] {processor.py:153} INFO - Started process (PID=11253) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:21:07,408] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:21:07,409] {logging_mixin.py:115} INFO - [2025-01-05 10:21:07,408] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:21:07,986] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:21:07,999] {logging_mixin.py:115} INFO - [2025-01-05 10:21:07,999] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:21:08,020] {logging_mixin.py:115} INFO - [2025-01-05 10:21:08,019] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:21:08,042] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.640 seconds
[2025-01-05 10:21:32,293] {processor.py:153} INFO - Started process (PID=11571) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:21:32,295] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:21:32,296] {logging_mixin.py:115} INFO - [2025-01-05 10:21:32,296] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:21:33,638] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:21:33,674] {logging_mixin.py:115} INFO - [2025-01-05 10:21:33,674] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:21:33,735] {logging_mixin.py:115} INFO - [2025-01-05 10:21:33,735] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:21:33,766] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.481 seconds
[2025-01-05 10:22:23,978] {processor.py:153} INFO - Started process (PID=12368) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:22:23,979] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:22:23,982] {logging_mixin.py:115} INFO - [2025-01-05 10:22:23,982] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:22:24,864] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:22:24,887] {logging_mixin.py:115} INFO - [2025-01-05 10:22:24,886] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:22:24,918] {logging_mixin.py:115} INFO - [2025-01-05 10:22:24,918] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:22:24,948] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.975 seconds
[2025-01-05 10:23:06,931] {processor.py:153} INFO - Started process (PID=12711) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:23:06,936] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:23:06,938] {logging_mixin.py:115} INFO - [2025-01-05 10:23:06,938] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:23:07,890] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:23:08,038] {logging_mixin.py:115} INFO - [2025-01-05 10:23:08,036] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:23:08,091] {logging_mixin.py:115} INFO - [2025-01-05 10:23:08,091] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:23:08,151] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.227 seconds
[2025-01-05 10:23:47,988] {processor.py:153} INFO - Started process (PID=13081) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:23:47,990] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:23:47,991] {logging_mixin.py:115} INFO - [2025-01-05 10:23:47,991] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:23:48,491] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:23:48,518] {logging_mixin.py:115} INFO - [2025-01-05 10:23:48,518] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:23:48,543] {logging_mixin.py:115} INFO - [2025-01-05 10:23:48,543] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:23:48,582] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.603 seconds
[2025-01-05 10:24:20,827] {processor.py:153} INFO - Started process (PID=13322) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:24:20,831] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:24:20,834] {logging_mixin.py:115} INFO - [2025-01-05 10:24:20,834] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:24:21,722] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:24:21,751] {logging_mixin.py:115} INFO - [2025-01-05 10:24:21,750] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:24:21,798] {logging_mixin.py:115} INFO - [2025-01-05 10:24:21,795] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:24:21,850] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.035 seconds
[2025-01-05 10:25:06,351] {processor.py:153} INFO - Started process (PID=13855) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:25:06,358] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:25:06,359] {logging_mixin.py:115} INFO - [2025-01-05 10:25:06,359] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:25:07,446] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:25:07,490] {logging_mixin.py:115} INFO - [2025-01-05 10:25:07,487] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:25:07,538] {logging_mixin.py:115} INFO - [2025-01-05 10:25:07,538] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:25:07,578] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.233 seconds
[2025-01-05 10:25:42,826] {processor.py:153} INFO - Started process (PID=13933) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:25:42,835] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:25:42,839] {logging_mixin.py:115} INFO - [2025-01-05 10:25:42,839] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:25:44,023] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:25:44,051] {logging_mixin.py:115} INFO - [2025-01-05 10:25:44,051] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:25:44,095] {logging_mixin.py:115} INFO - [2025-01-05 10:25:44,095] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:25:44,134] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.327 seconds
[2025-01-05 10:26:23,567] {processor.py:153} INFO - Started process (PID=14148) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:26:23,571] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:26:23,574] {logging_mixin.py:115} INFO - [2025-01-05 10:26:23,572] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:26:24,731] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:26:24,771] {logging_mixin.py:115} INFO - [2025-01-05 10:26:24,771] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:26:24,834] {logging_mixin.py:115} INFO - [2025-01-05 10:26:24,834] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:26:24,875] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.344 seconds
[2025-01-05 10:27:07,283] {processor.py:153} INFO - Started process (PID=14527) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:27:07,287] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:27:07,290] {logging_mixin.py:115} INFO - [2025-01-05 10:27:07,290] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:27:08,831] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:27:09,026] {logging_mixin.py:115} INFO - [2025-01-05 10:27:09,026] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:27:09,050] {logging_mixin.py:115} INFO - [2025-01-05 10:27:09,047] {dag.py:2398} INFO - Creating ORM DAG for weather_data
[2025-01-05 10:27:09,078] {logging_mixin.py:115} INFO - [2025-01-05 10:27:09,078] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:27:09,170] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.904 seconds
[2025-01-05 10:27:48,678] {processor.py:153} INFO - Started process (PID=14799) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:27:48,682] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:27:48,682] {logging_mixin.py:115} INFO - [2025-01-05 10:27:48,682] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:27:49,607] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:27:49,630] {logging_mixin.py:115} INFO - [2025-01-05 10:27:49,630] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:27:49,667] {logging_mixin.py:115} INFO - [2025-01-05 10:27:49,667] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:27:49,702] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.036 seconds
[2025-01-05 10:28:23,203] {processor.py:153} INFO - Started process (PID=14911) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:28:23,210] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:28:23,211] {logging_mixin.py:115} INFO - [2025-01-05 10:28:23,211] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:28:24,327] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:28:24,430] {logging_mixin.py:115} INFO - [2025-01-05 10:28:24,430] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:28:24,479] {logging_mixin.py:115} INFO - [2025-01-05 10:28:24,478] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-23T00:00:00+00:00, run_after=2024-12-30T00:00:00+00:00
[2025-01-05 10:28:24,530] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.345 seconds
[2025-01-05 10:29:02,882] {processor.py:153} INFO - Started process (PID=15339) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:29:02,890] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:29:02,890] {logging_mixin.py:115} INFO - [2025-01-05 10:29:02,890] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:29:04,378] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:29:04,442] {logging_mixin.py:115} INFO - [2025-01-05 10:29:04,438] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:29:04,606] {logging_mixin.py:115} INFO - [2025-01-05 10:29:04,603] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:29:04,691] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.825 seconds
[2025-01-05 10:29:55,786] {processor.py:153} INFO - Started process (PID=15489) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:29:55,794] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:29:55,798] {logging_mixin.py:115} INFO - [2025-01-05 10:29:55,798] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:30:00,054] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:30:00,198] {logging_mixin.py:115} INFO - [2025-01-05 10:30:00,198] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:30:00,438] {logging_mixin.py:115} INFO - [2025-01-05 10:30:00,438] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:30:00,654] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 4.900 seconds
[2025-01-05 10:31:36,807] {processor.py:153} INFO - Started process (PID=15778) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:31:36,811] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:31:36,812] {logging_mixin.py:115} INFO - [2025-01-05 10:31:36,812] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:31:37,646] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:31:37,669] {logging_mixin.py:115} INFO - [2025-01-05 10:31:37,669] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:31:37,693] {logging_mixin.py:115} INFO - [2025-01-05 10:31:37,693] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:31:37,713] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.910 seconds
[2025-01-05 10:32:10,137] {processor.py:153} INFO - Started process (PID=16025) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:32:10,138] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:32:10,138] {logging_mixin.py:115} INFO - [2025-01-05 10:32:10,138] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:32:10,482] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:32:10,524] {logging_mixin.py:115} INFO - [2025-01-05 10:32:10,524] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:32:10,548] {logging_mixin.py:115} INFO - [2025-01-05 10:32:10,548] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:32:10,570] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.436 seconds
[2025-01-05 10:32:44,161] {processor.py:153} INFO - Started process (PID=16381) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:32:44,162] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:32:44,163] {logging_mixin.py:115} INFO - [2025-01-05 10:32:44,162] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:32:44,587] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:32:44,629] {logging_mixin.py:115} INFO - [2025-01-05 10:32:44,628] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:32:44,633] {logging_mixin.py:115} INFO - [2025-01-05 10:32:44,633] {dag.py:2398} INFO - Creating ORM DAG for weather_data
[2025-01-05 10:32:44,649] {logging_mixin.py:115} INFO - [2025-01-05 10:32:44,649] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-16T00:00:00+00:00, run_after=2024-12-23T00:00:00+00:00
[2025-01-05 10:32:44,667] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.509 seconds
[2025-01-05 10:33:18,766] {processor.py:153} INFO - Started process (PID=16744) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:33:18,768] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:33:18,769] {logging_mixin.py:115} INFO - [2025-01-05 10:33:18,769] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:33:19,029] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:33:19,047] {logging_mixin.py:115} INFO - [2025-01-05 10:33:19,046] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:33:19,057] {logging_mixin.py:115} INFO - [2025-01-05 10:33:19,057] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:33:19,073] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.310 seconds
[2025-01-05 10:33:51,346] {processor.py:153} INFO - Started process (PID=16785) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:33:51,347] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:33:51,347] {logging_mixin.py:115} INFO - [2025-01-05 10:33:51,347] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:33:51,630] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:33:51,638] {logging_mixin.py:115} INFO - [2025-01-05 10:33:51,638] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:33:51,649] {logging_mixin.py:115} INFO - [2025-01-05 10:33:51,649] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:33:51,661] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.317 seconds
[2025-01-05 10:34:26,392] {processor.py:153} INFO - Started process (PID=16820) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:34:26,393] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:34:26,394] {logging_mixin.py:115} INFO - [2025-01-05 10:34:26,394] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:34:26,707] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:34:26,716] {logging_mixin.py:115} INFO - [2025-01-05 10:34:26,716] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:34:26,729] {logging_mixin.py:115} INFO - [2025-01-05 10:34:26,729] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:34:26,740] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.350 seconds
[2025-01-05 10:35:01,679] {processor.py:153} INFO - Started process (PID=16862) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:35:01,681] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:35:01,681] {logging_mixin.py:115} INFO - [2025-01-05 10:35:01,681] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:35:01,988] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:35:01,997] {logging_mixin.py:115} INFO - [2025-01-05 10:35:01,997] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:35:02,010] {logging_mixin.py:115} INFO - [2025-01-05 10:35:02,010] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:35:02,021] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.345 seconds
[2025-01-05 10:35:32,179] {processor.py:153} INFO - Started process (PID=16997) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:35:32,180] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:35:32,180] {logging_mixin.py:115} INFO - [2025-01-05 10:35:32,180] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:35:32,493] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:35:32,507] {logging_mixin.py:115} INFO - [2025-01-05 10:35:32,507] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:35:32,520] {logging_mixin.py:115} INFO - [2025-01-05 10:35:32,520] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:35:32,533] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.358 seconds
[2025-01-05 10:36:04,757] {processor.py:153} INFO - Started process (PID=17034) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:36:04,760] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:36:04,761] {logging_mixin.py:115} INFO - [2025-01-05 10:36:04,761] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:36:05,072] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:36:05,081] {logging_mixin.py:115} INFO - [2025-01-05 10:36:05,081] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:36:05,095] {logging_mixin.py:115} INFO - [2025-01-05 10:36:05,095] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:36:05,108] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.354 seconds
[2025-01-05 10:36:38,487] {processor.py:153} INFO - Started process (PID=17075) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:36:38,488] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:36:38,488] {logging_mixin.py:115} INFO - [2025-01-05 10:36:38,488] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:36:38,815] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:36:38,825] {logging_mixin.py:115} INFO - [2025-01-05 10:36:38,824] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:36:38,839] {logging_mixin.py:115} INFO - [2025-01-05 10:36:38,839] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:36:38,852] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.371 seconds
[2025-01-05 10:37:12,466] {processor.py:153} INFO - Started process (PID=17118) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:37:12,467] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:37:12,468] {logging_mixin.py:115} INFO - [2025-01-05 10:37:12,468] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:37:12,821] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:37:12,832] {logging_mixin.py:115} INFO - [2025-01-05 10:37:12,832] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:37:12,844] {logging_mixin.py:115} INFO - [2025-01-05 10:37:12,844] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:37:12,859] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.396 seconds
[2025-01-05 10:37:50,233] {processor.py:153} INFO - Started process (PID=17215) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:37:50,235] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:37:50,236] {logging_mixin.py:115} INFO - [2025-01-05 10:37:50,236] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:37:50,855] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:37:50,867] {logging_mixin.py:115} INFO - [2025-01-05 10:37:50,867] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:37:50,889] {logging_mixin.py:115} INFO - [2025-01-05 10:37:50,889] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:37:50,905] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.676 seconds
[2025-01-05 10:38:33,443] {processor.py:153} INFO - Started process (PID=17530) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:38:33,447] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:38:33,449] {logging_mixin.py:115} INFO - [2025-01-05 10:38:33,449] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:38:34,489] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:38:34,516] {logging_mixin.py:115} INFO - [2025-01-05 10:38:34,516] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:38:34,563] {logging_mixin.py:115} INFO - [2025-01-05 10:38:34,563] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:38:34,603] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.167 seconds
[2025-01-05 10:39:14,681] {processor.py:153} INFO - Started process (PID=17567) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:39:14,685] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:39:14,687] {logging_mixin.py:115} INFO - [2025-01-05 10:39:14,687] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:39:15,483] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:39:15,517] {logging_mixin.py:115} INFO - [2025-01-05 10:39:15,517] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:39:15,551] {logging_mixin.py:115} INFO - [2025-01-05 10:39:15,551] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:39:15,583] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.910 seconds
[2025-01-05 10:39:46,731] {processor.py:153} INFO - Started process (PID=17728) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:39:46,732] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:39:46,732] {logging_mixin.py:115} INFO - [2025-01-05 10:39:46,732] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:39:47,947] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:39:47,995] {logging_mixin.py:115} INFO - [2025-01-05 10:39:47,993] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:39:48,060] {logging_mixin.py:115} INFO - [2025-01-05 10:39:48,060] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:39:48,123] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.419 seconds
[2025-01-05 10:40:33,292] {processor.py:153} INFO - Started process (PID=18125) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:40:33,296] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:40:33,300] {logging_mixin.py:115} INFO - [2025-01-05 10:40:33,300] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:40:34,339] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:40:34,376] {logging_mixin.py:115} INFO - [2025-01-05 10:40:34,376] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:40:34,441] {logging_mixin.py:115} INFO - [2025-01-05 10:40:34,440] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:40:34,495] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.208 seconds
[2025-01-05 10:45:08,555] {processor.py:153} INFO - Started process (PID=18347) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:45:08,561] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:45:08,562] {logging_mixin.py:115} INFO - [2025-01-05 10:45:08,561] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:45:10,198] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:45:10,251] {logging_mixin.py:115} INFO - [2025-01-05 10:45:10,251] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:45:10,345] {logging_mixin.py:115} INFO - [2025-01-05 10:45:10,345] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:45:10,393] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.843 seconds
[2025-01-05 10:45:47,328] {processor.py:153} INFO - Started process (PID=18677) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:45:47,330] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:45:47,331] {logging_mixin.py:115} INFO - [2025-01-05 10:45:47,331] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:45:47,809] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:45:47,824] {logging_mixin.py:115} INFO - [2025-01-05 10:45:47,823] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:45:47,852] {logging_mixin.py:115} INFO - [2025-01-05 10:45:47,851] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:45:47,879] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.556 seconds
[2025-01-05 10:46:25,729] {processor.py:153} INFO - Started process (PID=18833) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:46:25,730] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:46:25,731] {logging_mixin.py:115} INFO - [2025-01-05 10:46:25,731] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:46:26,209] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:46:26,227] {logging_mixin.py:115} INFO - [2025-01-05 10:46:26,227] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:46:26,250] {logging_mixin.py:115} INFO - [2025-01-05 10:46:26,250] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:46:26,265] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.539 seconds
[2025-01-05 10:47:04,293] {processor.py:153} INFO - Started process (PID=19151) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:47:04,296] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:47:04,297] {logging_mixin.py:115} INFO - [2025-01-05 10:47:04,297] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:47:04,729] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:47:04,742] {logging_mixin.py:115} INFO - [2025-01-05 10:47:04,742] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:47:04,767] {logging_mixin.py:115} INFO - [2025-01-05 10:47:04,766] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:47:04,782] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.496 seconds
[2025-01-05 10:47:42,310] {processor.py:153} INFO - Started process (PID=19313) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:47:42,311] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:47:42,312] {logging_mixin.py:115} INFO - [2025-01-05 10:47:42,312] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:47:42,774] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:47:42,787] {logging_mixin.py:115} INFO - [2025-01-05 10:47:42,787] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:47:42,806] {logging_mixin.py:115} INFO - [2025-01-05 10:47:42,806] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:47:42,822] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.518 seconds
[2025-01-05 10:52:13,203] {processor.py:153} INFO - Started process (PID=3523) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:52:13,206] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:52:13,207] {logging_mixin.py:115} INFO - [2025-01-05 10:52:13,207] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:52:14,543] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:52:14,570] {logging_mixin.py:115} INFO - [2025-01-05 10:52:14,569] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:52:14,596] {logging_mixin.py:115} INFO - [2025-01-05 10:52:14,596] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:52:14,622] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 1.429 seconds
[2025-01-05 10:52:54,371] {processor.py:153} INFO - Started process (PID=3899) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:52:54,372] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:52:54,372] {logging_mixin.py:115} INFO - [2025-01-05 10:52:54,372] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:52:54,621] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:52:54,644] {logging_mixin.py:115} INFO - [2025-01-05 10:52:54,644] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:52:54,648] {logging_mixin.py:115} INFO - [2025-01-05 10:52:54,648] {dag.py:2398} INFO - Creating ORM DAG for weather_data
[2025-01-05 10:52:54,656] {logging_mixin.py:115} INFO - [2025-01-05 10:52:54,656] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-16T00:00:00+00:00, run_after=2024-12-23T00:00:00+00:00
[2025-01-05 10:52:54,670] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.302 seconds
[2025-01-05 10:53:25,816] {processor.py:153} INFO - Started process (PID=3939) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:53:25,817] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:53:25,817] {logging_mixin.py:115} INFO - [2025-01-05 10:53:25,817] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:53:26,109] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:53:26,118] {logging_mixin.py:115} INFO - [2025-01-05 10:53:26,118] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:53:26,128] {logging_mixin.py:115} INFO - [2025-01-05 10:53:26,128] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-16T00:00:00+00:00, run_after=2024-12-23T00:00:00+00:00
[2025-01-05 10:53:26,138] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.326 seconds
[2025-01-05 10:53:56,850] {processor.py:153} INFO - Started process (PID=3974) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:53:56,851] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:53:56,851] {logging_mixin.py:115} INFO - [2025-01-05 10:53:56,851] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:53:57,095] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:53:57,103] {logging_mixin.py:115} INFO - [2025-01-05 10:53:57,102] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:53:57,113] {logging_mixin.py:115} INFO - [2025-01-05 10:53:57,113] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-16T00:00:00+00:00, run_after=2024-12-23T00:00:00+00:00
[2025-01-05 10:53:57,122] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.275 seconds
[2025-01-05 10:54:33,025] {processor.py:153} INFO - Started process (PID=4017) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:54:33,027] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:54:33,027] {logging_mixin.py:115} INFO - [2025-01-05 10:54:33,027] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:54:33,308] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:54:33,317] {logging_mixin.py:115} INFO - [2025-01-05 10:54:33,316] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:54:33,328] {logging_mixin.py:115} INFO - [2025-01-05 10:54:33,327] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-16T00:00:00+00:00, run_after=2024-12-23T00:00:00+00:00
[2025-01-05 10:54:33,341] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.318 seconds
[2025-01-05 10:55:04,199] {processor.py:153} INFO - Started process (PID=4058) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:55:04,201] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:55:04,201] {logging_mixin.py:115} INFO - [2025-01-05 10:55:04,201] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:55:04,613] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:55:04,625] {logging_mixin.py:115} INFO - [2025-01-05 10:55:04,624] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:55:04,641] {logging_mixin.py:115} INFO - [2025-01-05 10:55:04,640] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-16T00:00:00+00:00, run_after=2024-12-23T00:00:00+00:00
[2025-01-05 10:55:04,651] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.456 seconds
[2025-01-05 10:55:37,872] {processor.py:153} INFO - Started process (PID=4101) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:55:37,873] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:55:37,875] {logging_mixin.py:115} INFO - [2025-01-05 10:55:37,875] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:55:38,155] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:55:38,164] {logging_mixin.py:115} INFO - [2025-01-05 10:55:38,164] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:55:38,175] {logging_mixin.py:115} INFO - [2025-01-05 10:55:38,175] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-16T00:00:00+00:00, run_after=2024-12-23T00:00:00+00:00
[2025-01-05 10:55:38,187] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.318 seconds
[2025-01-05 10:56:09,404] {processor.py:153} INFO - Started process (PID=4145) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:56:09,405] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:56:09,405] {logging_mixin.py:115} INFO - [2025-01-05 10:56:09,405] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:56:09,725] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:56:09,750] {logging_mixin.py:115} INFO - [2025-01-05 10:56:09,749] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:56:09,771] {logging_mixin.py:115} INFO - [2025-01-05 10:56:09,771] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-16T00:00:00+00:00, run_after=2024-12-23T00:00:00+00:00
[2025-01-05 10:56:09,794] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.394 seconds
[2025-01-05 10:56:45,755] {processor.py:153} INFO - Started process (PID=4193) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:56:45,756] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:56:45,756] {logging_mixin.py:115} INFO - [2025-01-05 10:56:45,756] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:56:46,096] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:56:46,105] {logging_mixin.py:115} INFO - [2025-01-05 10:56:46,104] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:56:46,118] {logging_mixin.py:115} INFO - [2025-01-05 10:56:46,118] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-16T00:00:00+00:00, run_after=2024-12-23T00:00:00+00:00
[2025-01-05 10:56:46,129] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.377 seconds
[2025-01-05 10:57:19,640] {processor.py:153} INFO - Started process (PID=4289) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:57:19,643] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:57:19,643] {logging_mixin.py:115} INFO - [2025-01-05 10:57:19,643] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:57:20,024] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:57:20,036] {logging_mixin.py:115} INFO - [2025-01-05 10:57:20,035] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:57:20,052] {logging_mixin.py:115} INFO - [2025-01-05 10:57:20,052] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-16T00:00:00+00:00, run_after=2024-12-23T00:00:00+00:00
[2025-01-05 10:57:20,067] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.430 seconds
[2025-01-05 10:57:56,448] {processor.py:153} INFO - Started process (PID=4559) to work on /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:57:56,449] {processor.py:641} INFO - Processing file /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py for tasks to queue
[2025-01-05 10:57:56,450] {logging_mixin.py:115} INFO - [2025-01-05 10:57:56,450] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:57:56,902] {processor.py:651} INFO - DAG(s) dict_keys(['weather_data']) retrieved from /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py
[2025-01-05 10:57:56,912] {logging_mixin.py:115} INFO - [2025-01-05 10:57:56,912] {dag.py:2379} INFO - Sync 1 DAGs
[2025-01-05 10:57:56,930] {logging_mixin.py:115} INFO - [2025-01-05 10:57:56,930] {dag.py:2927} INFO - Setting next_dagrun for weather_data to 2024-12-30T00:00:00+00:00, run_after=2025-01-06T00:00:00+00:00
[2025-01-05 10:57:56,954] {processor.py:161} INFO - Processing /home/daniel/Documents/Alura/python_apache_airflow_pipeline/dags/weather_data.py took 0.511 seconds
